version: '3'

services:
  qdb:
    image: mariadb:10.3
    container_name: qdb
    environment:
      - TZ=$TZ
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PWD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_USER_PWD
    ports:
      - 3306:3306
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d:ro
      - mysql:/var/lib/mysql
    command: ["--character_set_server=utf8", "--lower_case_table_names=1"]

  qems:
    build:
      context: qems
      args:
        WEBHOME: $WEBHOME
        APIHOME: $APIHOME
    image: tomcat:qems
    container_name: qems
    depends_on:
      - qdb
    environment:
      - TZ=$TZ
      - WEBHOME=$WEBHOME
      - APIHOME=$APIHOME
      - CATALINA_HOME=
    ports:
      - 8081:8081
    volumes:
      - ./logw:${WEBHOME}/logs
      - ./loga:${APIHOME}/logs
    logging:
      driver: "none"
    command: bash -c "
      echo > /dev/tcp/qdb/3306; while [ $$? -ne 0 ]; do echo > /dev/tcp/qdb/3306; sleep 2; done
      && echo \"127.0.0.1 qems\" >> /etc/hosts
      && /usr/local/tomcat_api/bin/catalina.sh start
      && /usr/local/tomcat/bin/catalina.sh run
      "

volumes:
  mysql:
